### ISSUE TITLE
persistence.xml is required but doc claims its optional

### ISSUE THREAD

**Issue by elonderin** [jpdigital/hibernate5-ddl-maven-plugin#10]
this is what i get when there is no persistance.xml
note inconsistency of log vs. error.

```
...
[INFO] persistence.xml available, locking for properties...
[ERROR] Failed to open persistence.xml. Not processing properties.
java.io.FileNotFoundException: D:\DEV\CODE\trunk\src\main\resources\META-INF\persistence.xml (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)```

**Comment by abhishekmundewal** [comment]
Hi Elonderin, 
Did you find any solution for this problem, since I'm also facing the same. Any help would be highly appreciated.

**Comment by jpdigital** [comment]
The latest version (2.0.4) now checks if the persistence.xml is available before accessing it. 

Can please try and check is the problem solved for you?

**Comment by jpdigital** [comment]
No reaction. Assuming this is fixed now.
