### ISSUE TITLE
Add org.hibernate.dialect.MySQL57Dialect

### ISSUE THREAD

**Issue by tavish** [jpdigital/hibernate5-ddl-maven-plugin#12]
Please add the org.hibernate.dialect.MySQL57Dialect dialect.

**Comment by jpdigital** [comment]
The MySQL57Dialect has been added to the last version 2.0.4 which is available since today.

**Comment by tavish** [comment]
Only the following are defined for MySQL Dialects:
```java
    ...
    MYSQL("org.hibernate.dialect.MySQLDialect"),
    MYSQL_INNODB("org.hibernate.dialect.MySQLInnoDBDialect"),
    MYSQL_MYISAM("org.hibernate.dialect.MySQLMyISAMDialect"),
    MYSQL5("org.hibernate.dialect.MySQL5Dialect"),
    MYSQL5_INNODB("org.hibernate.dialect.MySQL5InnoDBDialect"),
    MYSQL57_INNODB("org.hibernate.dialect.MySQL57InnoDBDialect"),
    ...
```
([Dialect.java:62-67](https://github.com/jpdigital/hibernate5-ddl-maven-plugin/blob/hibernate5-ddl-maven-plugin-2.0.4/hibernate5-ddl-maven-plugin-core/src/main/java/de/jpdigital/maven/plugins/hibernate5ddl/Dialect.java#L62-L67))

`MYSQL57("org.hibernate.dialect.MySQL57Dialect")` is not in this list.
