### ISSUE TITLE
Plugin takes artifact from local repo instead of target/classes and generates empty script.

### ISSUE THREAD

**Issue by Tibor17** [jpdigital/hibernate5-ddl-maven-plugin#15]
I have a single Maven module project.
If I run `mvn install` then generated resources are packaged and installed to local repo.
The second run of `mvn install` takes *.jar file from Local Repo and can see that postgresql9.sql presents and thus generates empty script in `target/generated-resources`.

**Comment by Tibor17** [comment]
@jpdigital 
Your plugin reads classes from jar in Local Repo or from `target/classes`?

**Comment by Tibor17** [comment]
@jpdigital 
I found the problem. Your plugin binds the `goal: compile` to Maven phase `compile`. 
I checked your Mojo classes and it looks fine to me `PROCESS_CLASSES("process-classes")` but the problem is how the plugin descriptor is generated:

{quote}
<mojos>
    <mojo>
      <goal>compile</goal>
      <description>Compiles application sources</description>
      <requiresDependencyResolution>compile</requiresDependencyResolution>
      <requiresDirectInvocation>false</requiresDirectInvocation>
      <requiresProject>true</requiresProject>
      <requiresReports>false</requiresReports>
      <aggregator>false</aggregator>
      <requiresOnline>false</requiresOnline>
      <inheritedByDefault>true</inheritedByDefault>
      <phase>compile</phase>
{quote}

If you could not define the phase then it would be up to us users to define it.

**Comment by jpdigital** [comment]
I created a simple project myself and tried to reproduce this problem, but for my everything worked fine. I tried various combinations of clean, package and install. Also I made changes to the entity in the project. In every case I had a SQL file with the expected content in `target/generated-resources`. 

Which version of the plugin did you use? And which version of Maven? Also it would be helpful if you could provide a simple example which shows the issue.

**Comment by Tibor17** [comment]
Now I am using another for HB 5.2
`hibernate52-ddl-maven-plugin:2.1.0`.

I think it required some trick.
We had to clean and install the module, and then only install second time.
