### ISSUE TITLE
Allow configurable output file

### ISSUE THREAD

**Issue by MatthewEdge** [jpdigital/hibernate5-ddl-maven-plugin#16]
Currently in core the SQL file generation is based off of the dialect chosen:

```
return Paths.get(String.format(
            "%s/%s.sql", dirPath, dialect.name().toLowerCase(Locale.ENGLISH)));
```

It would be nice to have this configurable via a property. Something like:

```
@Parameter(required = false)
private String outputFileName;
```

If not provided then you'd use the dialect name as is and continue to support multiple dialect generations but the presence of the property would allow for single-dialect cases where we want to generate a specific file (for example Spring folk would use this to generate a `data.sql` file on the classpath).

Thoughts?

**Comment by MatthewEdge** [comment]
And it looks like PR #11 started that idea but makes the outputFileName required x)

**Comment by jpdigital** [comment]
Thanks for suggestion. Version 2.1.0 introduces several options for customising the path and the name of the generated files. You can find details on the project page.
