### ISSUE TITLE
DDL generation fails when cache region factory cannot be found on class path

### ISSUE THREAD

**Issue by JWGmeligMeyling** [jpdigital/hibernate5-ddl-maven-plugin#18]
When my `persistence.xml` contains the following caching configuration:

```xml
      <property name="hibernate.cache.use_second_level_cache" value="true" />
      <property name="hibernate.cache.use_query_cache" value="true" />
      <property name="hibernate.cache.infinispan.statistics" value="true"/>
      <property name="hibernate.cache.region.factory_class" value="org.hibernate.cache.infinispan.InfinispanRegionFactory"/>
      <property name="hibernate.transaction.factory_class" value="org.hibernate.transaction.JTATransactionFactory"/>
      <property name="hibernate.transaction.manager_lookup_class" value="org.hibernate.transaction.JBossTransactionManagerLookup"/>
      <property name="hibernate.cache.infinispan.cfg" value="infinispan-config.xml"/>
```

The DDL generation fails with:

```
[ERROR] Failed to execute goal de.jpdigital:hibernate52-ddl-maven-plugin:2.0.4:gen-ddl (default-cli) on project domain: Execution default-cli of goal de.jpdigital:hibernate52-ddl-maven-plugin:2.0.4:gen-ddl failed: Unable to create requested service [org.hibernate.cache.spi.RegionFactory]: Unable to resolve name [org.hibernate.cache.infinispan.InfinispanRegionFactory] as strategy [org.hibernate.cache.spi.RegionFactory] -> [Help 1]
```

It was quite easy to workaround as I could temporarily disable caching for DDL generation, plus that it is possible to specify the `persistence.xml` configuration file that should be used. Nevertheless it got me wondering, perhaps the plugin should construct the `persistence.xml` on its own using the provided package?

**Comment by jpdigital** [comment]
The problem is that some of the properties might need to be passed to the Hibernate Schema Generator by the plugin to create a correct schema. For example if you are using Envers you can change the Audit Strategy used by Envers using a property. The value of that property effect the schema.

But I looks like that there are some properties which are not needed and might cause to schema generation to fail. A solution for that will be in the next release (2.2.0).

**Comment by jpdigital** [comment]
I just uploaded version 2.2.0 of the plugin to the central repository. Can you please check the changes in the release solve this issue for you?

**Comment by JWGmeligMeyling** [comment]
Verified and it works now, thanks for addressing this! 👍
