### ISSUE TITLE
How to configure plugin for use with model classes under src/test/java ?

### ISSUE THREAD

**Issue by archiecobbs** [jpdigital/hibernate5-ddl-maven-plugin#19]
I have a need to use this plugin only during tests. I have some model classes (under `src/test/java`) that are _only_ used for testing, and want to generate DDL on them prior to running the tests so that some unit tests can test some automated query generation stuff.

It's not clear that this is possible with this plugin; or, if it is possible, it's not documented anywhere.

I tried configuring `<phase>process-test-classes</phase>` but that didn't work - nothing was generated because apparently the plugin is still looking under `src/main/java` for source files.

I see that it's possible and documented to generate DDL for tests based on `src/main/java` classes, but I don't want my test model classes to be in the main JAR; they are only used for testing.

Thanks.

**Comment by jpdigital** [comment]
I have added a new parameter `includeTestClasses`. If set to `true` entities in src/test are included into the generated schema. This feature will be part of the 2.3 release.

**Comment by archiecobbs** [comment]
@jpdigital, awesome - thanks!
