### ISSUE TITLE
persistence.xml is not optional as documented

### ISSUE THREAD

**Issue by rodrik** [jpdigital/hibernate5-ddl-maven-plugin#2]
When persistence.xml is not found, the following error occurs:
java.io.FileNotFoundException: src\main\resources\META-INF\persistence.xml (The system cannot find the file specified)

The documentation says: If the file is not present it is ignored.

**Comment by rodrik** [comment]
Ok, I noticed that the error is displayed but the build succeeds. No issue!

**Comment by jandhollander** [comment]
If the file is ignored if it isn't found, please don't write out the stacktrace.

Performing the build *successfully* shouldn't show any stacktraces. At the most, show a *warning* that the file isn't found and gets ignored.
