### ISSUE TITLE
`useEnvers` not available as configuration anymore

### ISSUE THREAD

**Issue by dkellenb** [jpdigital/hibernate5-ddl-maven-plugin#23]
On the documentation site (http://jpdigital.github.io/hibernate5-ddl-maven-plugin/usage.html) following configuration is proposed to enable *envers*:

```xml
<configuration>
  <dialects>
    <param>postgresql9</param>
  </dialects>
  <useEnvers>true</useEnvers>
  <packages>
    <param>org.example.entities</param>
  </packages>
</configuration>
```

But looking at `GenerateDdlMojo` there is no `useEnvers` parameter. How can i enable schema generation with envers?

**Comment by jpdigital** [comment]
Thanks for spotting that. The mentioning of `useEnvers` was a leftover from earlier versions. The usage of Envers is detected automatically by Hibernate. In current HEAD `useEnvers` has been removed.
