### ISSUE TITLE
Update and support hibernate V 5.3 And Java 9

### ISSUE THREAD

**Issue by unknowedNp** [jpdigital/hibernate5-ddl-maven-plugin#24]
Please update To support hibernate 53 and java 9 and later
in java 9 this error occurred
javax.xml.bind not found exception

im solve this to add dependency to plugin
                    <dependency>
                        <groupId>javax.xml.bind</groupId>
                        <artifactId>jaxb-api</artifactId>
                        <version>2.3.0</version>
                    </dependency>
                    <dependency>
                        <groupId>com.sun.xml.bind</groupId>
                        <artifactId>jaxb-core</artifactId>
                        <version>2.3.0.1</version>
                    </dependency>
                    <dependency>
                        <groupId>com.sun.xml.bind</groupId>
                        <artifactId>jaxb-impl</artifactId>
                        <version>2.3.0.1</version>
                    </dependency>
                    <dependency>
                        <groupId>javax.activation</groupId>
                        <artifactId>javax.activation-api</artifactId>
                        <version>1.2.0</version>
                    </dependency>

please keep alive project

**Comment by JWGmeligMeyling** [comment]
I have no issue running the 5.2 version of the plugin against Hibernate 5.3 or even 5.4, so I think this issue is mostly about supporting Java 9 with the removed XML dependencies from the JDK.

You can easily add those dependencies in the `<dependencies>` tag of the plugin-configuration in your `pom.xml` file as a workaround.

**Comment by jpdigital** [comment]
Hibernate 5.3 and 5.4 are now supported and the dependencies for JAXB have been included into all variants.
