### ISSUE TITLE
@Converter annotated classes are ignored

### ISSUE THREAD

**Issue by pado83** [jpdigital/hibernate5-ddl-maven-plugin#25]
@Converter annotated classes with autoapply = true are ignored, this affect sql for fields with converter that changes sql type. For example enums are mapped by default as int but my converter maps it to String.

I suppose that you have to change EntityFinder class to discover also @Converter annotated classes and pass them to Hibernate.

I tried to annotate my converter with @Entity (it is wrong, I know...), your plugin discovered it, and the sql was correct.

**Comment by jpdigital** [comment]
Thanks for your report and the pull request. I just merged the pull request. The next version will support Converter classes.
