### ISSUE TITLE
Add drop-create support

### ISSUE THREAD

**Issue by lgueye** [jpdigital/hibernate5-ddl-maven-plugin#4]
Hi all,

I could not find the support for drop first statements.
I use them for idempotency.

Thank you a lot

**Comment by jpdigital** [comment]
Hello Igueye,

support for creating the Drop statements is already their: http://jpdigital.github.io/hibernate5-ddl-maven-plugin/gen-ddl-mojo.html#createDropStatements
You only have to enable it in the plugin configuration.

Best regards

Jens

**Comment by lgueye** [comment]
Again, my bad really sorry for 2 wrongly filed issue.
This one can also be closed.

And many thanks for the plugin which is pretty much the only one to provide a simple integration to hibernate 5.x

**Comment by jpdigital** [comment]
Hello Igueye,

no problem. That option is bit hidden in the documentation. In the next release I will add an example page to the documentation to make these things easier to find.

Best regards

Jens
