### ISSUE TITLE
HikariCPConnectionProvider

### ISSUE THREAD

**Issue by jjohanning** [jpdigital/hibernate5-ddl-maven-plugin#9]
HikariCPConnectionProvider let the build fail

persistence.xml:

<property name="hibernate.connection.provider_class" value="org.hibernate.hikaricp.internal.HikariCPConnectionProvider" />

error:

[ERROR] HikariPool-1 - dataSource or dataSourceClassName or jdbcUrl is required.

Failed to execute goal de.jpdigital:hibernate5-ddl-maven-plugin:1.0.1-hibernate-5.2.4.Final:gen-ddl (default-cli) on project auti-server: Execution default-cli of goal de.jpdigital:hibernate5-ddl-maven-plugin:1.0.1-hibernate-5.2.4.Final:gen-ddl failed: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]: java.lang.IllegalArgumentException: dataSource or dataSourceClassName or jdbcUrl is required.

**Comment by jpdigital** [comment]
Can you please provide a full persistence.xml or maybe a simple example project? This would help me to reproduce the issue.

**Comment by jpdigital** [comment]
Closed because no example was provided. I have no experience with the Hikari Connection Provider. For issues like these please provide a full example so that I can reproduce the issue.
